title = 'Enumerate Cliques'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/820"

[[tests]]
	name = "example.in"
	number = 2
[[tests]]
	name = "minimum.in"
	number = 1
[[tests]]
	name = "small_sparse.cpp"
	number = 3
[[tests]]
	name = "small_dense.cpp"
	number = 3
[[tests]]
	name = "large_sparse.cpp"
	number = 5
[[tests]]
	name = "large_random.cpp"
	number = 3
[[tests]]
	name = "max_random.cpp"
	number = 3
[[tests]]
	name = "star.cpp"
	number = 2
[[tests]]
	name = "max_complete.cpp"
	number = 1

[[solutions]]
	name = 'naive.cpp'
	expect = "WA"
	allow_tle = true

[params]
	N_MIN = 1
	N_MAX = 100
	M_MIN = 1
	M_MAX = 100
	MOD = 998_244_353
